### PR TITLE
Updates to changes api

### PR DESCRIPTION
**Pull request by dhruvsoni1802**

### CODE REVIEW

**Comment by dhruvsoni1802** [comment]
So i was trying to rebase my forked repo with the original one that's why these 87 commits are there

**Comment by jchris** [comment]
when that happens to me, I've been known to get my known state I want to have the branch at in one window, and a clean checkout (different code space?) in another window, and just do the changes for that pr by hand in a new branch. I have done this many times...

**Comment by jchris** [comment]
tagging https://github.com/fireproof-storage/fireproof/issues/21

**Comment by jchris** [comment]
Closing this b/c it is drifted out of date. We should still clean up the changes response type. The relevant commit is here: https://github.com/fireproof-storage/fireproof/pull/33/commits/2f44f485e600dc2db569713108e56c15a73a5f2a

**Pull request closed without merging**
